name: Checkout

on: [ push ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: '14'
          run: npx cypress run

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx cypress run

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          screenshotOnRunFailure: true
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload video
        uses: actions/upload-artifact@v3
        with:
          videoCompression: true
          videosFolder: cypress/video