name: Checkout

on: [ push ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: '14'
          run: npx cypress run

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run test